"""
Django settings for films_backend project.
Generated by 'django-admin startproject' using Django 4.2.6.
For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Chargement des variables d'environnement depuis .env
env_path = Path(__file__).resolve().parent.parent / '.env'
load_dotenv(env_path)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Vous devrez définir cette variable dans les paramètres de votre projet Vercel
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-g)hz$pnmc@5tnrq43u$2w**+17sk1z#0klovi+bsiykt1779g2"
)

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG sera 'False' sur Vercel par défaut
DEBUG = os.environ.get("DEBUG", "False") == "True"

# L'URL de production sera ajoutée automatiquement par Vercel.
ALLOWED_HOSTS = ["127.0.0.1", ".vercel.app", "localhost"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "Base_threlte_dv",
    "films",
    "taggit",
]

# Configuration de l'API REST
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    # Personnalisation de l'interface navigable
    'DEFAULT_METADATA_CLASS': 'rest_framework.metadata.SimpleMetadata',
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.AcceptHeaderVersioning',
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    # Documentation de l'API
    'DEFAULT_TITLE': 'API Films et Géométries',
    'DEFAULT_DESCRIPTION': '''
    API de gestion des films et des géométries.
    
    Endpoints disponibles:
    - /api/films/ : Gestion des films
    - /api/geometries/ : Gestion des géométries
    - /api/types/ : Liste des types disponibles
    - /api/upload/ : Gestion des uploads
    ''',
    'SERVE_INCLUDE_SCHEMA': True,
}

# Personnalisation de l'interface d'administration
ADMIN_SITE_HEADER = "Administration du Film Service"
ADMIN_SITE_TITLE = "Film Service Admin"
ADMIN_INDEX_TITLE = "Gestion des Films et Géométries"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Configuration pour utiliser SQLite en local et PostgreSQL en production via une URL.
# Vous devrez définir DATABASE_URL dans les variables d'environnement de Vercel.

# Configuration de la base de données avec Neon
DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql://neondb_owner:npg_zKtQE5JVDU0R@ep-lucky-truth-agdq4088-pooler.c-2.eu-central-1.aws.neon.tech/neondb"
)

# Parse l'URL de la base de données
db_config = dj_database_url.parse(DATABASE_URL)

# Ajout des paramètres SSL spécifiques pour Neon
# Neon requiert SSL pour toutes les connexions
db_config.setdefault('OPTIONS', {})
db_config['OPTIONS'].update({
    'sslmode': 'require',
    'connect_timeout': 10,
})

# Pour les connexions poolées, s'assurer que SSL est bien configuré
if 'sslmode' not in db_config.get('OPTIONS', {}):
    db_config['OPTIONS']['sslmode'] = 'require'

DATABASES = {
    "default": db_config
}

# Configuration des connexions pour la performance
if DATABASE_URL and 'neon' in DATABASE_URL:
    # Configuration spécifique pour Neon DB avec pooling
    DATABASES['default'].update({
        'CONN_MAX_AGE': 600,  # Réutiliser les connexions pendant 10 minutes
        'OPTIONS': {
            **DATABASES['default'].get('OPTIONS', {}),
            'connect_timeout': 10,
        }
    })

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files configuration
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files configuration
# Les fichiers média sont stockés localement en développement
# En production, utilisez Vercel Blob Storage
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Configuration Vercel Blob Storage
BLOB_READ_WRITE_TOKEN = os.environ.get("BLOB_READ_WRITE_TOKEN")
VERCEL_BLOB_STORE_ID = os.environ.get("STORE_ID", "your-store-id")

# Correction du warning Django URLField (Django 6.0)
FORMS_URLFIELD_ASSUME_HTTPS = True

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = True  # Only for development
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = []  # Initialisation de la liste

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Vercel définit automatiquement cette variable d'environnement
VERCEL_URL = os.environ.get("VERCEL_URL")

if VERCEL_URL:
    CORS_ALLOWED_ORIGINS.append(f"https://{VERCEL_URL}")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
