<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /home/ubt/DpDIST/Web_site_3D_anime_By_DV/static/models/DcYcU.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/DcYcU.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.PointLight intensity={54351.41} decay={2} position={[4.08, 5.9, -1.01]} rotation={[-1.84, 0.6, 1.93]} />
    <T.PerspectiveCamera
      makeDefault={false}
      far={100}
      near={0.1}
      fov={22.9}
      position={[7.36, 4.96, 6.93]}
      rotation={[-0.63, 0.71, 0.44]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube.geometry}
      material={gltf.materials.Material}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={[-1, -2.68, -1]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube001.geometry}
      material={gltf.materials.Material}
      position={[0, 2.48, -2.88]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={[-1, -2.68, -1]}
    />
    
    <T.Mesh geometry={gltf.nodes.Sphère.geometry} material={gltf.materials.Matériau} position={[4.13, 0, 0]} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
