# Generated by Django 5.1.2 on 2025-11-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='image',
        ),
        migrations.AddField(
            model_name='film',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
